### ISSUE TITLE
Enhancement: Multiple Input Types

### ISSUE THREAD

**Issue by Azrael3000** [shuhaowu/pvpyfilter#1]
Hi,

first, thanks for this little tool. It works great and has helped me tremendously.

It would be perfect if we could specify more than one input data type. ParaView allows multiple declarations of <DataType value="..."/> in the xml file, so if your tool would support it by having the input_data_type as an array, that would be perfect.

Cheers,
Arno

**Comment by shuhaowu** [comment]
I'm not sure what you mean. Can you give me an example?

**Comment by Azrael3000** [comment]
Sure. In the current pvpyfilter py configuration file I specify:

```
input_data_type  = "vtkPolyData"
```

which is converted by pvpyfilter to

```
<DataTypeDomain name="input_type">
  <DataType value="vtkPolyData"/>
</DataTypeDomain>
```

in the resulting filter xml script. As my filter can work not only with vtkPolyData but also other formats I would like a feature that allows me to do something like this:

```
input_data_type  = ["vtkPolyData", "vtkMultiBlockData", "vtkUnstructuredGrid"]
```

which gets converted to 

```
<DataTypeDomain name="input_type">
  <DataType value="vtkPolyData"/>
  <DataType value="vtkMultiBlockData"/>
  <DataType value="vtkUnstructuredGrid"/>
</DataTypeDomain>
```

I currently have to add these additional entries manually, so I know that the xml code works as above. It would be great though, if pvpyfilter could do it automagically.

I hope that makes my feature request clearer. If you have any questions, let me know.
Cheers,
Arno

**Comment by shuhaowu** [comment]
Do you think you can modify this and send a PR? This should be a really easy fix, but I currently don't have the time to code and test a solution. 

The necessary thing you have to modify is here:

https://github.com/shuhaowu/pvpyfilter/blob/d3331f9dad5aedca9574c108119aa7c2820b9127/pvpyfilter.py#L318

I believe you can simply use change it such that you append multiple of these `DataType`. The one caveat is the need to see if `cls.input_data_type` is an array or a string, which then triggers the correct behaviour to preserve backward compatibility.

**Comment by Azrael3000** [comment]
I have the same time constraints unfortunately. I'll see if I can fix it on a weekend. Thanks for the hint anyways.

**Comment by Azrael3000** [comment]
[0001-Allow-lists-as-input_data_type-implements-issue-1.patch.txt](https://github.com/shuhaowu/pvpyfilter/files/2041419/0001-Allow-lists-as-input_data_type-implements-issue-1.patch.txt)

use `git am 0001-Allow-lists-as-input_data_type-implements-issue-1.patch.txt` to commit it to your branch and push it. Avoids me having to create a fork and all that stuff :) Feel free to close this issue. Thanks for the hint with line 318.

**Comment by shuhaowu** [comment]
Thanks a lot!
