### ISSUE TITLE
Enhancement: Add vtkMultiPieceDataSet as output option

### ISSUE THREAD

**Issue by Azrael3000** [shuhaowu/pvpyfilter#2]
[0001-Add-vtkMultiPieceDataSet-as-output-option.txt](https://github.com/shuhaowu/pvpyfilter/files/2860929/0001-Add-vtkMultiPieceDataSet-as-output-option.txt)

Use `git am` to install like last time. Does exactly what the title says.

Cheers,
Arno

**Comment by shuhaowu** [comment]
Can you send a PR and tag me with @shuhaowu? I didn't even see this for a long time.

**Comment by shuhaowu** [comment]
Actually I just did it. Next time please send a PR and tag me so I get an email about it.

**Comment by Azrael3000** [comment]
sure no problem. Thanks
